### ISSUE TITLE
Optimize the forgotten easy case of division by power-of-two

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [stevenhoving/integer_division#2]
https://github.com/stevenhoving/integer_division/blob/master/integer_division_uint8.h show results that are technically correct for powers-of-two, although they can be obviously much simpler.

As we all know here, dividing by 2^n is just right shift by n bits. Current implementation shifts left by 7, then right by 8, then right by n-1.

Some compilers for regular platforms will most certainly simplify and generate code for the one simple shift.

Simpler compilers, especially for embedded machines which needs this kind of hack more than others, may not generate optimal assembly.

One might say "these are compile-time macros, if the divisor is a power of two, just do the usual shift".

Still, this is especially interesting for usage where the source code calling those macros is not written by a human but generated by some preprocessing step. 

Also this work can be a basis for a division by a variable not known at compile time, via a table lookup of parameters. This case needs power-of-two to be handled also.

**Comment by stevenhoving** [comment]
Hi, thanks for the interest in this 'archive' repository, but I have to disappoint you. I currently have no plans for active development on the code in this repository. The reason for this is simple, long time ago when I was searching for integer division by multiplication I stumbled upon a book called [Hackers Delight](http://www.hackersdelight.org). In this book there was this chapter (I think it was chapter 10) describing how to do a integer division by multiplication. Eventually I found out that this was an ancient method commonly used by embedded programmers (back in the old days) on systems that did not had hardware integer division. And there was a blog post describing it (which possibly was the source of the hackers delight chapter). After I discovered that this blog post was no where to be found I turned to the internet archive to recover it, but for some reason the source files that came with this blog post was not archived. Eventually I found them, and decided to archive it for posterity.
So feel free to fork this repository and fix those issues, but besides creating an example on how to use these headers #1 I do not have any interests in active development in the near future. I hope you can understand.

**Comment by fidergo-stephane-gourichon** [comment]
> So feel free to fork this repository and fix those issues, but besides creating an example on how to use these headers #1 I do not have any interests in active development in the near future. I hope you can understand.

Thank you for your reply. Yes, I understand. Opening those issues does not imply that I expect you to work on them. Actually, I was opening them as a marker/reminder, in order to possibly do that work later for integration in [cpcitor/cpc-dev-tool-chain: A development toolchain to compile your modern C or assembly projects on a modern OS and run on an Amstrad CPC or emulator.](https://github.com/cpcitor/cpc-dev-tool-chain "cpcitor/cpc-dev-tool-chain: A development toolchain to compile your modern C or assembly projects on a modern OS and run on an Amstrad CPC or emulator.")

I was expecting you to let the issues stay open as a public signal that there is room for improvement for anyone who might want to do it. IMHO closing the 3 issues suggests that you consider there is nothing interesting to do at all, or at least that you don't consider merging pull-requests.

In that case, I may sooner or later fork as you suggested, open the same issues on my fork and maybe work on them.  Thank you again for your reply.

**Comment by cpcitor** [comment]
Forked to https://github.com/cpcitor/integer_division .

**Comment by stevenhoving** [comment]
I'm sorry @fidergo-stephane-gourichon I didn't want to start on a bad foot by closing your issues. I just do not intent to change anything in that repository because its only purpose is to only archive the blogpost and the source code that came with it. So that others like yourself can fork/use it.

**Comment by fidergo-stephane-gourichon** [comment]
Do not worry. :-)

> its only purpose is to only archive the blogpost and the source code that came with it. So that others like yourself can fork/use it.

That's a pretty good purpose. It served it well and I thank you for that. 

May I suggest something? The suggestion is, as some repositories with similar "archival-only" purposes do, to in the beginning of the `Readme.md`,  (1) state that purpose (2) tell visitors not to open issues or offer PRs, but consider visiting [forks](https://github.com/stevenhoving/integer_division/network/members) for activity and do issues and PR there.
